name: Cleanup Resources
on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "destroy" to confirm resource deletion'
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_STATE_BUCKET_NAME: ${{ secrets.AWS_TF_STATE_BUCKET_NAME }}
  AWS_REGION: us-east-1

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirmation == 'destroy'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=$TF_STATE_BUCKET_NAME" -backend-config="region=$AWS_REGION"
        working-directory: ./terraform

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform

      - name: Delete ECR Repository
        run: |
          aws ecr delete-repository --repository-name first-node-app --force || echo "Repository already deleted or doesn't exist"